<?php

declare(strict_types=1);

namespace Mollie\Zed\Mollie\Communication\Form;

use Spryker\Zed\Gui\Communication\Table\AbstractTable;
use Spryker\Zed\Kernel\Communication\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Choice;

class ApiKeyForm extends AbstractType
{
    public const string FIELD_TEST_KEY = 'test_key';
    public const string FIELD_LIVE_KEY = 'live_key';
    public const string FIELD_STORES = 'stores';
    public const string OPTION_STORE_CHOICES = 'store_choices';

    /**
     * @param OptionsResolver $resolver
     *
     * @return void
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     *
     * @return void
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this
            ->addLiveApiKeyField($builder)
            ->addTestApiKeyField($builder)
//            ->addStoresField($builder, $options[static::OPTION_STORE_CHOICES]);
;

        $storeChoices = $options[static::OPTION_STORE_CHOICES];
        if ($storeChoices) {
            $this->addStoresField($builder, $storeChoices);
        }
    }

    /**
     * @param FormBuilderInterface $builder
     *
     * @return $this
     */
    protected function addLiveApiKeyField(FormBuilderInterface $builder)
    {
        $builder->add(static::FIELD_LIVE_KEY, PasswordType::class, [
            'label' => 'Live api key',
        ]);

        return $this;
    }

    /**
     * @param FormBuilderInterface $builder
     *
     * @return $this
     */
    protected function addTestApiKeyField(FormBuilderInterface $builder)
    {
        $builder->add(static::FIELD_TEST_KEY, PasswordType::class, [
            'label' => 'Test api key',
        ]);

        return $this;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $choices
     *
     * @return $this
     */
    protected function addStoresField(FormBuilderInterface $builder, array $choices)
    {
        $builder->add(static::FIELD_STORES, ChoiceType::class, [
            'constraints' => [
                new Choice([
                    'choices' => array_keys($choices),
                    'multiple' => true,
                ]),
            ],
            'label' => 'Use live for stores',
            'multiple' => true,
            'expanded' => true,
            'choices' => array_flip($choices),
        ]);

        return $this;
    }


}